version: '3.5'
services:
  mysql:
    image: mysql
    container_name: mysqldb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: nbm
#    volumes:
#      - ./mysql-data:/var/lib/mysql

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: always
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafkaserver:
    image: 'bitnami/kafka:latest'
    restart: always
    container_name: kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1

  nginx-proxy:
    build: image/nginx-proxy
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80" # to remove
      - "443:443"
    volumes:
      - /usr/docker/nginx/ssl:/etc/nginx/ssl

  secure-bank-api-auth:
    build: ../secure-bank-api-auth
#    image: 'secure-bank-api-auth'
    restart: always
    container_name: secure-bank-api-auth
    depends_on:
      - mysql

  secure-bank-api-transfer:
#    image: 'secure-bank-api-transfer:1.0'
    build: ../secure-bank-api-transfer
    restart: always
    container_name: secure-bank-api-transfer
    depends_on:
      - secure-bank-api-auth

  secure-bank-api-currency-exchange:
#    image: 'secure-bank-api-currency-exchange:1.0'
    build: ../secure-bank-api-currency-exchange
    restart: always
    container_name: secure-bank-api-currency-exchange
    depends_on:
      - secure-bank-api-auth