FROM eclipse-temurin:17-jdk-alpine
COPY target/secure-bank-api-currency-exchange-1.0-exec.jar secure-bank-api-currency-exchange-1.0.jar
ENTRYPOINT ["java","-jar","/secure-bank-api-currency-exchange-1.0.jar"]